/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MinhasRifasRouteImport } from './routes/minhas-rifas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RifaIdRouteImport } from './routes/rifa.$id'
import { Route as AdminVendaBalcaoRouteImport } from './routes/admin.venda-balcao'
import { Route as AdminSorteiosRouteImport } from './routes/admin.sorteios'
import { Route as AdminRifasRouteImport } from './routes/admin.rifas'
import { Route as AdminRifasIndexRouteImport } from './routes/admin.rifas.index'
import { Route as AdminRifasNovaRouteImport } from './routes/admin.rifas.nova'
import { Route as AdminRifasIdRouteImport } from './routes/admin.rifas.$id'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasRifasRoute = MinhasRifasRouteImport.update({
  id: '/minhas-rifas',
  path: '/minhas-rifas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RifaIdRoute = RifaIdRouteImport.update({
  id: '/rifa/$id',
  path: '/rifa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendaBalcaoRoute = AdminVendaBalcaoRouteImport.update({
  id: '/venda-balcao',
  path: '/venda-balcao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSorteiosRoute = AdminSorteiosRouteImport.update({
  id: '/sorteios',
  path: '/sorteios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRifasRoute = AdminRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRifasIndexRoute = AdminRifasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRifasRoute,
} as any)
const AdminRifasNovaRoute = AdminRifasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminRifasRoute,
} as any)
const AdminRifasIdRoute = AdminRifasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRifasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/rifas': typeof AdminRifasRouteWithChildren
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/venda-balcao': typeof AdminVendaBalcaoRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/admin/rifas/nova': typeof AdminRifasNovaRoute
  '/admin/rifas/': typeof AdminRifasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/venda-balcao': typeof AdminVendaBalcaoRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/admin/rifas/nova': typeof AdminRifasNovaRoute
  '/admin/rifas': typeof AdminRifasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/rifas': typeof AdminRifasRouteWithChildren
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/venda-balcao': typeof AdminVendaBalcaoRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/admin/rifas/nova': typeof AdminRifasNovaRoute
  '/admin/rifas/': typeof AdminRifasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/login'
    | '/minhas-rifas'
    | '/politica-de-privacidade'
    | '/register'
    | '/termos-de-uso'
    | '/admin/rifas'
    | '/admin/sorteios'
    | '/admin/venda-balcao'
    | '/rifa/$id'
    | '/admin/'
    | '/admin/rifas/$id'
    | '/admin/rifas/nova'
    | '/admin/rifas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/login'
    | '/minhas-rifas'
    | '/politica-de-privacidade'
    | '/register'
    | '/termos-de-uso'
    | '/admin/sorteios'
    | '/admin/venda-balcao'
    | '/rifa/$id'
    | '/admin'
    | '/admin/rifas/$id'
    | '/admin/rifas/nova'
    | '/admin/rifas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/login'
    | '/minhas-rifas'
    | '/politica-de-privacidade'
    | '/register'
    | '/termos-de-uso'
    | '/admin/rifas'
    | '/admin/sorteios'
    | '/admin/venda-balcao'
    | '/rifa/$id'
    | '/admin/'
    | '/admin/rifas/$id'
    | '/admin/rifas/nova'
    | '/admin/rifas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  LoginRoute: typeof LoginRoute
  MinhasRifasRoute: typeof MinhasRifasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RegisterRoute: typeof RegisterRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  RifaIdRoute: typeof RifaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-rifas': {
      id: '/minhas-rifas'
      path: '/minhas-rifas'
      fullPath: '/minhas-rifas'
      preLoaderRoute: typeof MinhasRifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rifa/$id': {
      id: '/rifa/$id'
      path: '/rifa/$id'
      fullPath: '/rifa/$id'
      preLoaderRoute: typeof RifaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venda-balcao': {
      id: '/admin/venda-balcao'
      path: '/venda-balcao'
      fullPath: '/admin/venda-balcao'
      preLoaderRoute: typeof AdminVendaBalcaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sorteios': {
      id: '/admin/sorteios'
      path: '/sorteios'
      fullPath: '/admin/sorteios'
      preLoaderRoute: typeof AdminSorteiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rifas': {
      id: '/admin/rifas'
      path: '/rifas'
      fullPath: '/admin/rifas'
      preLoaderRoute: typeof AdminRifasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rifas/': {
      id: '/admin/rifas/'
      path: '/'
      fullPath: '/admin/rifas/'
      preLoaderRoute: typeof AdminRifasIndexRouteImport
      parentRoute: typeof AdminRifasRoute
    }
    '/admin/rifas/nova': {
      id: '/admin/rifas/nova'
      path: '/nova'
      fullPath: '/admin/rifas/nova'
      preLoaderRoute: typeof AdminRifasNovaRouteImport
      parentRoute: typeof AdminRifasRoute
    }
    '/admin/rifas/$id': {
      id: '/admin/rifas/$id'
      path: '/$id'
      fullPath: '/admin/rifas/$id'
      preLoaderRoute: typeof AdminRifasIdRouteImport
      parentRoute: typeof AdminRifasRoute
    }
  }
}

interface AdminRifasRouteChildren {
  AdminRifasIdRoute: typeof AdminRifasIdRoute
  AdminRifasNovaRoute: typeof AdminRifasNovaRoute
  AdminRifasIndexRoute: typeof AdminRifasIndexRoute
}

const AdminRifasRouteChildren: AdminRifasRouteChildren = {
  AdminRifasIdRoute: AdminRifasIdRoute,
  AdminRifasNovaRoute: AdminRifasNovaRoute,
  AdminRifasIndexRoute: AdminRifasIndexRoute,
}

const AdminRifasRouteWithChildren = AdminRifasRoute._addFileChildren(
  AdminRifasRouteChildren,
)

interface AdminRouteChildren {
  AdminRifasRoute: typeof AdminRifasRouteWithChildren
  AdminSorteiosRoute: typeof AdminSorteiosRoute
  AdminVendaBalcaoRoute: typeof AdminVendaBalcaoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRifasRoute: AdminRifasRouteWithChildren,
  AdminSorteiosRoute: AdminSorteiosRoute,
  AdminVendaBalcaoRoute: AdminVendaBalcaoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  LoginRoute: LoginRoute,
  MinhasRifasRoute: MinhasRifasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RegisterRoute: RegisterRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  RifaIdRoute: RifaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
