/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MinhasRifasRouteImport } from './routes/minhas-rifas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RifaIdRouteImport } from './routes/rifa.$id'
import { Route as AdminRifasRouteImport } from './routes/admin.rifas'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasRifasRoute = MinhasRifasRouteImport.update({
  id: '/minhas-rifas',
  path: '/minhas-rifas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RifaIdRoute = RifaIdRouteImport.update({
  id: '/rifa/$id',
  path: '/rifa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRifasRoute = AdminRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/register': typeof RegisterRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/register': typeof RegisterRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minhas-rifas': typeof MinhasRifasRoute
  '/register': typeof RegisterRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/minhas-rifas'
    | '/register'
    | '/admin/rifas'
    | '/rifa/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/minhas-rifas'
    | '/register'
    | '/admin/rifas'
    | '/rifa/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/minhas-rifas'
    | '/register'
    | '/admin/rifas'
    | '/rifa/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MinhasRifasRoute: typeof MinhasRifasRoute
  RegisterRoute: typeof RegisterRoute
  RifaIdRoute: typeof RifaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-rifas': {
      id: '/minhas-rifas'
      path: '/minhas-rifas'
      fullPath: '/minhas-rifas'
      preLoaderRoute: typeof MinhasRifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rifa/$id': {
      id: '/rifa/$id'
      path: '/rifa/$id'
      fullPath: '/rifa/$id'
      preLoaderRoute: typeof RifaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rifas': {
      id: '/admin/rifas'
      path: '/rifas'
      fullPath: '/admin/rifas'
      preLoaderRoute: typeof AdminRifasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRifasRoute: typeof AdminRifasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRifasRoute: AdminRifasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MinhasRifasRoute: MinhasRifasRoute,
  RegisterRoute: RegisterRoute,
  RifaIdRoute: RifaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
